image: php:7.2-alpine

pipelines:
  default:
    - step:
        name: Test
        caches:
          - composer
        script:
          - apk update && apk add unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit
    - step:
        name: Sync repo to GitHub
        clone:
          depth: full
        script:
          - apk update && apk add git
          - apk update && apk add openssh-client
          - git push --mirror git@github.com:Piggy-Loyalty/piggy-php-sdk.git
